
services:
  open-tax-db:
    image: postgres:18
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  opentax-backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - open-tax-db
    volumes:
      - ./backend:/app
      - ./backend/config.toml:/app/config.toml
    command: sh -c "opentax seed && uvicorn presentation.api.main:app --host 0.0.0.0 --port 8000 --reload"
  opentax-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - opentax-backend
    volumes:
      - ./frontend:/app
    command: sh -c "npm run build && npm start"
volumes:
  postgres_data: